#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "lint-staged:"
npx lint-staged

export CI=true
echo
echo "React tests:"
npm run test

# source: https://raw.githubusercontent.com/google/yapf/main/plugins/pre-commit.sh
set +o posix
PYTHON_FILES=()
while IFS=$'\n' read -r line; do PYTHON_FILES+=("$line"); done \
  < <(git diff --name-only --cached --diff-filter=AM | grep --color=never '.py$')

if [ ${#PYTHON_FILES[@]} -ne 0 ]; then
  echo
  echo "yapf:"
  ./servers/duolingo/venv/bin/yapf -i -r "${PYTHON_FILES[@]}"

  CHANGED_FILES=()
  while IFS=$'\n' read -r line; do CHANGED_FILES+=("$line"); done \
    < <(git diff --name-only "${PYTHON_FILES[@]}")

  if [ ${#CHANGED_FILES[@]} -gt 0 ]; then
    echo 'Reformatted staged files. Please review and stage the changes.'
    echo 'Files updated: ' "${CHANGED_FILES[@]}"
    echo
    exit 1
  fi
fi
